App_Scaffold/config/routes.rb
Rails.application.routes.draw do

  root "estudiantes#index"

  resources :estudiantes

  resources :buys

  get "up" => "rails/health#show", as: :rails_health_check
end

App_Scaffold/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

App_Scaffold/app/models/buy.rb
class Buy < ApplicationRecord

  validates :category, :description, :amount, presence: true

end

App_Scaffold/app/models/estudiante.rb
class Estudiante < ApplicationRecord
  validates :nombres, presence: true
  validates :apellidos, presence: true
  validates :carrera, presence: true
  validates :carnet, presence: true
  validates :fecha_de_nacimiento, presence: true
  validates :edad, presence: true, numericality: { only_integer: true }
  validates :celular, presence: true, numericality: { only_integer: true }
end

App_Scaffold/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

App_Scaffold/app/controllers/buys_controller.rb
class BuysController < ApplicationController
  before_action :set_buy, only: %i[ show edit update destroy ]

  # GET /buys or /buys.json
  def index
    @buys = Buy.all
  end

  # GET /buys/1 or /buys/1.json
  def show
  end

  # GET /buys/new
  def new
    @buy = Buy.new
  end

  # GET /buys/1/edit
  def edit
  end

  # POST /buys or /buys.json
  def create
    @buy = Buy.new(buy_params)

    respond_to do |format|
      if @buy.save
        format.html { redirect_to buy_url(@buy), notice: "Buy was successfully created." }
        format.json { render :show, status: :created, location: @buy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buys/1 or /buys/1.json
  def update
    respond_to do |format|
      if @buy.update(buy_params)
        format.html { redirect_to buy_url(@buy), notice: "Buy was successfully updated." }
        format.json { render :show, status: :ok, location: @buy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @buy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buys/1 or /buys/1.json
  def destroy
    @buy.destroy!

    respond_to do |format|
      format.html { redirect_to buys_url, notice: "Buy was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buy
      @buy = Buy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def buy_params
      params.require(:buy).permit(:category, :description, :amount)
    end
end

App_Scaffold/app/controllers/estudiantes_controller.rb
class EstudiantesController < ApplicationController
  before_action :set_estudiante, only: %i[ show edit update destroy ]

  # GET /estudiantes or /estudiantes.json
  def index
    @estudiantes = Estudiante.all
  end

  # GET /estudiantes/1 or /estudiantes/1.json
  def show
  end

  # GET /estudiantes/new
  def new
    @estudiante = Estudiante.new
  end

  # GET /estudiantes/1/edit
  def edit
  end

  # POST /estudiantes or /estudiantes.json
  def create
    @estudiante = Estudiante.new(estudiante_params)

    respond_to do |format|
      if @estudiante.save
        format.html { redirect_to estudiante_url(@estudiante), notice: "Estudiante was successfully created." }
        format.json { render :show, status: :created, location: @estudiante }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /estudiantes/1 or /estudiantes/1.json
  def update
    respond_to do |format|
      if @estudiante.update(estudiante_params)
        format.html { redirect_to estudiante_url(@estudiante), notice: "Estudiante was successfully updated." }
        format.json { render :show, status: :ok, location: @estudiante }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @estudiante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estudiantes/1 or /estudiantes/1.json
  def destroy
    @estudiante.destroy!

    respond_to do |format|
      format.html { redirect_to estudiantes_url, notice: "Estudiante was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_estudiante
      @estudiante = Estudiante.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def estudiante_params
      params.require(:estudiante).permit(:nombres, :apellidos, :carrera, :carnet, :fecha_de_nacimiento, :edad, :celular)
    end
end

App_Scaffold/app/helpers/application_helper.rb
module ApplicationHelper
end

App_Scaffold/app/helpers/buys_helper.rb
module BuysHelper
end

App_Scaffold/app/helpers/estudiantes_helper.rb
module EstudiantesHelper
end

App_Scaffold/app/views/buys/_buy.html.erb
<div id="<%= dom_id buy %>">
  <p>
    <strong>Category:</strong>
    <%= buy.category %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= buy.description %>
  </p>

  <p>
    <strong>Amount:</strong>
    <%= buy.amount %>
  </p>

</div>

App_Scaffold/app/views/buys/_form.html.erb
<%= form_with(model: buy) do |form| %>
  <% if buy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(buy.errors.count, "error") %> prohibited this buy from being saved:</h2>

      <ul>
        <% buy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :category, style: "display: block" %>
    <%= form.text_field :category %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :amount, style: "display: block" %>
    <%= form.text_field :amount %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

App_Scaffold/app/views/buys/edit.html.erb
<h1>Editing buy</h1>

<%= render "form", buy: @buy %>

<br>

<div>
  <%= link_to "Show this buy", @buy %> |
  <%= link_to "Back to buys", buys_path %>
</div>

App_Scaffold/app/views/buys/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Buys</h1>

<div id="buys">
  <% @buys.each do |buy| %>
    <%= render buy %>
    <p>
      <%= link_to "Show this buy", buy %>
    </p>
  <% end %>
</div>

<%= link_to "New buy", new_buy_path %>

App_Scaffold/app/views/buys/new.html.erb
<h1>New buy</h1>

<%= render "form", buy: @buy %>

<br>

<div>
  <%= link_to "Back to buys", buys_path %>
</div>

App_Scaffold/app/views/buys/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @buy %>

<div>
  <%= link_to "Edit this buy", edit_buy_path(@buy) %> |
  <%= link_to "Back to buys", buys_path %>

  <%= button_to "Destroy this buy", @buy, method: :delete %>
</div>

App_Scaffold/app/views/estudiantes/_estudiante.html.erb
<div id="<%= dom_id estudiante %>">
  <p>
    <strong>Nombres:</strong>
    <%= estudiante.nombres %>
  </p>

  <p>
    <strong>Apellidos:</strong>
    <%= estudiante.apellidos %>
  </p>

  <p>
    <strong>Carrera:</strong>
    <%= estudiante.carrera %>
  </p>

  <p>
    <strong>Carnet:</strong>
    <%= estudiante.carnet %>
  </p>

  <p>
    <strong>Fecha de nacimiento:</strong>
    <%= estudiante.fecha_de_nacimiento %>
  </p>

  <p>
    <strong>Edad:</strong>
    <%= estudiante.edad %>
  </p>

  <p>
    <strong>Celular:</strong>
    <%= estudiante.celular %>
  </p>

</div>

App_Scaffold/app/views/estudiantes/_form.html.erb
<%= form_with(model: estudiante) do |form| %>
  <% if estudiante.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(estudiante.errors.count, "error") %> prohibited this estudiante from being saved:</h2>

      <ul>
        <% estudiante.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombres, style: "display: block" %>
    <%= form.text_field :nombres %>
  </div>

  <div>
    <%= form.label :apellidos, style: "display: block" %>
    <%= form.text_field :apellidos %>
  </div>

  <div>
    <%= form.label :carrera, style: "display: block" %>
    <%= form.text_field :carrera %>
  </div>

  <div>
    <%= form.label :carnet, style: "display: block" %>
    <%= form.text_field :carnet %>
  </div>

  <div>
    <%= form.label :fecha_de_nacimiento, style: "display: block" %>
    <%= form.date_field :fecha_de_nacimiento %>
  </div>

  <div>
    <%= form.label :edad, style: "display: block" %>
    <%= form.number_field :edad %>
  </div>

  <div>
    <%= form.label :celular, style: "display: block" %>
    <%= form.text_field :celular %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

App_Scaffold/app/views/estudiantes/edit.html.erb
<h1>Editing estudiante</h1>

<%= render "form", estudiante: @estudiante %>

<br>

<div>
  <%= link_to "Show this estudiante", @estudiante %> |
  <%= link_to "Back to estudiantes", estudiantes_path %>
</div>

App_Scaffold/app/views/estudiantes/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Estudiantes</h1>

<div id="estudiantes">
  <% @estudiantes.each do |estudiante| %>
    <%= render estudiante %>
    <p>
      <%= link_to "Show this estudiante", estudiante %>
    </p>
  <% end %>
</div>

<%= link_to "New estudiante", new_estudiante_path %>

App_Scaffold/app/views/estudiantes/new.html.erb
<h1>New estudiante</h1>

<%= render "form", estudiante: @estudiante %>

<br>

<div>
  <%= link_to "Back to estudiantes", estudiantes_path %>
</div>

App_Scaffold/app/views/estudiantes/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @estudiante %>

<div>
  <%= link_to "Edit this estudiante", edit_estudiante_path(@estudiante) %> |
  <%= link_to "Back to estudiantes", estudiantes_path %>

  <%= button_to "Destroy this estudiante", @estudiante, method: :delete %>
</div>

App_Scaffold/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppScaffold</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>